/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisasRouteImport } from './routes/visas'
import { Route as TemoignagesRouteImport } from './routes/temoignages'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PolitiqueRemboursementRouteImport } from './routes/politique-remboursement'
import { Route as MotDePasseOublieRouteImport } from './routes/mot-de-passe-oublie'
import { Route as MonCompteRouteImport } from './routes/mon-compte'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as InscriptionRouteImport } from './routes/inscription'
import { Route as GalerieRouteImport } from './routes/galerie'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DestinationsRouteImport } from './routes/destinations'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as ConditionsRouteImport } from './routes/conditions'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'

const VisasRoute = VisasRouteImport.update({
  id: '/visas',
  path: '/visas',
  getParentRoute: () => rootRouteImport,
} as any)
const TemoignagesRoute = TemoignagesRouteImport.update({
  id: '/temoignages',
  path: '/temoignages',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitiqueRemboursementRoute = PolitiqueRemboursementRouteImport.update({
  id: '/politique-remboursement',
  path: '/politique-remboursement',
  getParentRoute: () => rootRouteImport,
} as any)
const MotDePasseOublieRoute = MotDePasseOublieRouteImport.update({
  id: '/mot-de-passe-oublie',
  path: '/mot-de-passe-oublie',
  getParentRoute: () => rootRouteImport,
} as any)
const MonCompteRoute = MonCompteRouteImport.update({
  id: '/mon-compte',
  path: '/mon-compte',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const InscriptionRoute = InscriptionRouteImport.update({
  id: '/inscription',
  path: '/inscription',
  getParentRoute: () => rootRouteImport,
} as any)
const GalerieRoute = GalerieRouteImport.update({
  id: '/galerie',
  path: '/galerie',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsRoute = DestinationsRouteImport.update({
  id: '/destinations',
  path: '/destinations',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const ConditionsRoute = ConditionsRouteImport.update({
  id: '/conditions',
  path: '/conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/conditions': typeof ConditionsRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/connexion': typeof ConnexionRoute
  '/contact': typeof ContactRoute
  '/destinations': typeof DestinationsRoute
  '/faq': typeof FaqRoute
  '/galerie': typeof GalerieRoute
  '/inscription': typeof InscriptionRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/mon-compte': typeof MonCompteRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/politique-remboursement': typeof PolitiqueRemboursementRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/temoignages': typeof TemoignagesRoute
  '/visas': typeof VisasRoute
  '/admin/dashboard': typeof AdminDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/conditions': typeof ConditionsRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/connexion': typeof ConnexionRoute
  '/contact': typeof ContactRoute
  '/destinations': typeof DestinationsRoute
  '/faq': typeof FaqRoute
  '/galerie': typeof GalerieRoute
  '/inscription': typeof InscriptionRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/mon-compte': typeof MonCompteRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/politique-remboursement': typeof PolitiqueRemboursementRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/temoignages': typeof TemoignagesRoute
  '/visas': typeof VisasRoute
  '/admin/dashboard': typeof AdminDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/conditions': typeof ConditionsRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/connexion': typeof ConnexionRoute
  '/contact': typeof ContactRoute
  '/destinations': typeof DestinationsRoute
  '/faq': typeof FaqRoute
  '/galerie': typeof GalerieRoute
  '/inscription': typeof InscriptionRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/mon-compte': typeof MonCompteRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/politique-remboursement': typeof PolitiqueRemboursementRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/temoignages': typeof TemoignagesRoute
  '/visas': typeof VisasRoute
  '/admin/dashboard': typeof AdminDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/conditions'
    | '/confidentialite'
    | '/connexion'
    | '/contact'
    | '/destinations'
    | '/faq'
    | '/galerie'
    | '/inscription'
    | '/mentions-legales'
    | '/mon-compte'
    | '/mot-de-passe-oublie'
    | '/politique-remboursement'
    | '/reset-password'
    | '/services'
    | '/temoignages'
    | '/visas'
    | '/admin/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/conditions'
    | '/confidentialite'
    | '/connexion'
    | '/contact'
    | '/destinations'
    | '/faq'
    | '/galerie'
    | '/inscription'
    | '/mentions-legales'
    | '/mon-compte'
    | '/mot-de-passe-oublie'
    | '/politique-remboursement'
    | '/reset-password'
    | '/services'
    | '/temoignages'
    | '/visas'
    | '/admin/dashboard'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/conditions'
    | '/confidentialite'
    | '/connexion'
    | '/contact'
    | '/destinations'
    | '/faq'
    | '/galerie'
    | '/inscription'
    | '/mentions-legales'
    | '/mon-compte'
    | '/mot-de-passe-oublie'
    | '/politique-remboursement'
    | '/reset-password'
    | '/services'
    | '/temoignages'
    | '/visas'
    | '/admin/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  ConditionsRoute: typeof ConditionsRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  ConnexionRoute: typeof ConnexionRoute
  ContactRoute: typeof ContactRoute
  DestinationsRoute: typeof DestinationsRoute
  FaqRoute: typeof FaqRoute
  GalerieRoute: typeof GalerieRoute
  InscriptionRoute: typeof InscriptionRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  MonCompteRoute: typeof MonCompteRoute
  MotDePasseOublieRoute: typeof MotDePasseOublieRoute
  PolitiqueRemboursementRoute: typeof PolitiqueRemboursementRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ServicesRoute: typeof ServicesRoute
  TemoignagesRoute: typeof TemoignagesRoute
  VisasRoute: typeof VisasRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visas': {
      id: '/visas'
      path: '/visas'
      fullPath: '/visas'
      preLoaderRoute: typeof VisasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/temoignages': {
      id: '/temoignages'
      path: '/temoignages'
      fullPath: '/temoignages'
      preLoaderRoute: typeof TemoignagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politique-remboursement': {
      id: '/politique-remboursement'
      path: '/politique-remboursement'
      fullPath: '/politique-remboursement'
      preLoaderRoute: typeof PolitiqueRemboursementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mot-de-passe-oublie': {
      id: '/mot-de-passe-oublie'
      path: '/mot-de-passe-oublie'
      fullPath: '/mot-de-passe-oublie'
      preLoaderRoute: typeof MotDePasseOublieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mon-compte': {
      id: '/mon-compte'
      path: '/mon-compte'
      fullPath: '/mon-compte'
      preLoaderRoute: typeof MonCompteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscription': {
      id: '/inscription'
      path: '/inscription'
      fullPath: '/inscription'
      preLoaderRoute: typeof InscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galerie': {
      id: '/galerie'
      path: '/galerie'
      fullPath: '/galerie'
      preLoaderRoute: typeof GalerieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations': {
      id: '/destinations'
      path: '/destinations'
      fullPath: '/destinations'
      preLoaderRoute: typeof DestinationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conditions': {
      id: '/conditions'
      path: '/conditions'
      fullPath: '/conditions'
      preLoaderRoute: typeof ConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  ConditionsRoute: ConditionsRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  ConnexionRoute: ConnexionRoute,
  ContactRoute: ContactRoute,
  DestinationsRoute: DestinationsRoute,
  FaqRoute: FaqRoute,
  GalerieRoute: GalerieRoute,
  InscriptionRoute: InscriptionRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  MonCompteRoute: MonCompteRoute,
  MotDePasseOublieRoute: MotDePasseOublieRoute,
  PolitiqueRemboursementRoute: PolitiqueRemboursementRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ServicesRoute: ServicesRoute,
  TemoignagesRoute: TemoignagesRoute,
  VisasRoute: VisasRoute,
  AdminDashboardRoute: AdminDashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
